### ISSUE TITLE
为什么我在训练sv-cam++的时候loss越来越大

### ISSUE THREAD

**Issue by 2217895330** [alibaba-damo-academy/3D-Speaker#10]

**Comment by wanghuii1** [comment]
麻烦提供更多的使用细节信息，包括所用的训练数据规模、说话人数，是否更改了训练配置，最后测试的eer是否正常

**Comment by 2217895330** [comment]
有一些改动，说话人数量我设置为5613，但是在processor那一块没有加rir,noise,rir_noise，只是单纯用Voxceleb2的部分训练数据集去跑模型。这有影响吗？

**Comment by 2217895330** [comment]
在cam++.yaml这个文件中，因为只用Voxceleb2的数据集，没有加噪音，所有#inputs这里就把noise和reverb去掉了

**Comment by 2217895330** [comment]
数据规模在20G左右，由于loss一直变大，5~6个epoch之后loss显示为nan，所有就没有往下进行测试和评估指标
