### ISSUE TITLE
数据集

### ISSUE THREAD

**Issue by wangsheng3** [alibaba-damo-academy/3D-Speaker#103]
我换成自己的数据集，但是不知道，数据集要做哪些操作，能不能提供一下需要准备关于数据集的准备工作，包括与数据集相关的文件的获得方式什么的？

**Comment by yfchenlucky** [comment]
需要准备wav.scp, utt2spk等文件，具体细节可以参考代码：https://github.com/alibaba-damo-academy/3D-Speaker/blob/main/egs/3dspeaker/sv-eres2netv2/local/prepare_data.sh

**Comment by wangsheng3** [comment]
那wav.scp，utt2spk文件怎么生成的，你指出的代码里面只对这两个文件进行使用，但是没说怎么生成这两文件吧？

**Comment by yfchenlucky** [comment]
需要你自己准备，wav.scp按 utt path 格式生成; utt2spk按 utt spk格式生成。
