### ISSUE TITLE
ERes2Net模型 load报错

### ISSUE THREAD

**Issue by xiaodiandian1234** [alibaba-damo-academy/3D-Speaker#11]
在用torch.load 载入模型speech_eres2net_sv_zh-cn_16k-common时，报错_pickle.UnpicklingError: invalid load key, '\x08'.。请问下这个有遇到过吗？环境信息：Python 3.10.9、torch 1.12.1。
而用同样的代码载入speech_campplus_sv_zh-cn_16k-common这个模型就没问题

**Comment by yfchenlucky** [comment]
没有遇到过这种情况，刚刚测试使用torch.load命令，一切正常。你可以把代码和报错全部提交上来，帮你看一下。
Python 3.7.0 (default, Oct  9 2018, 10:31:47) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
>>> model = torch.load("/mnt/workspace/code/temp/speech_eres2net_sv_zh-cn_16k-common/pretrained_eres2net_aug.ckpt")
>>> torch.__version__
'1.12.0+cu102'

**Comment by xiaodiandian1234** [comment]
抱歉，是我的问题。现在可以了，多谢
