### ISSUE TITLE
SELF-DISTILLATION NETWORK WITH ENSEMBLE PROTOTYPES: LEARNING ROBUST SPEAKER REPRESENTATIONS WITHOUT SUPERVISION

### ISSUE THREAD

**Issue by gancx** [alibaba-damo-academy/3D-Speaker#115]
Thanks for your contribution to speaker verification and open-source code. I wonder if the bin/train_sdpn.py corresponds to the paper (SELF-DISTILLATION NETWORK WITH ENSEMBLE PROTOTYPES: LEARNING ROBUST SPEAKER REPRESENTATIONS WITHOUT SUPERVISION). They look quite similar but slightly different.

**Comment by yfchenlucky** [comment]
The code and the paper content do not match exactly but are very similar. The latest version of the paper will be open-sourced in June. Thank you for your attention. If it is helpful, please star and cite it.

**Comment by gancx** [comment]
> The code and the paper content do not match exactly but are very similar. The latest version of the paper will be open-sourced in June. Thank you for your attention. If it is helpful, please star and cite it.

Thanks for your prompt reply.
