### ISSUE TITLE
compute_score_metrics.py 输入参数？

### ISSUE THREAD

**Issue by zdj97** [alibaba-damo-academy/3D-Speaker#12]
speaklab/bin下的compute_score_metrics.py输入输出参数具体是什么呢？有没有样例参考参考。。感谢~

**Comment by yfchenlucky** [comment]
python speakerlab/bin/compute_score_metrics.py --enrol_data $exp_dir/embeddings --test_data $exp_dir/embeddings --scores_dir $exp_dir/scores --trials $trials
输入enroll和test提取完毕的embedding和trials，输出得分文件和计算结果。

**Comment by zdj97** [comment]
trials具体内容可以给个参考吗

**Comment by yfchenlucky** [comment]
id10270/x6uYqmx31kE/00001.wav id10270/8jEAjG6SegY/00008.wav target
id10270/x6uYqmx31kE/00001.wav id10300/ize_eiCFEg0/00003.wav nontarget
你可以从run.sh中的stage1开始跑，这样数据准备，训练模型都是一键运行的，然后再看里面的细节。
