### ISSUE TITLE
小白请教一下这段代码

### ISSUE THREAD

**Issue by Juelianqvq** [alibaba-damo-academy/3D-Speaker#132]
https://github.com/modelscope/3D-Speaker/blob/main/speakerlab/models/campplus/layers.py#L109

Does it imply that seg.shape[-1] should be less than x.shape[-1]? 

If not so, https://github.com/modelscope/3D-Speaker/blob/main/speakerlab/models/campplus/layers.py#L98 will certainly raise an error.

Is this the underlying relationship between x and seg?

**Comment by wanghuii1** [comment]
Before https://github.com/modelscope/3D-Speaker/blob/ab22112d280fed17839094da3874813c9eb63460/speakerlab/models/campplus/layers.py#L109, seg.shape[-1] is more than or equal to x.shape[-1]. Therefore, https://github.com/modelscope/3D-Speaker/blob/ab22112d280fed17839094da3874813c9eb63460/speakerlab/models/campplus/layers.py#L109 make seg and x the same shape.

**Comment by wanghuii1** [comment]
@Juelianqvq 
there is no chance for seg.shape[-1] < x.shape[-1]  based on the code https://github.com/modelscope/3D-Speaker/blob/ab22112d280fed17839094da3874813c9eb63460/speakerlab/models/campplus/layers.py#L108
