### ISSUE TITLE
我用达摩院提供的cam++预训练模型在vox1-o数据集上提取embedding计算eer是0.8666，而论文里是0.7几

### ISSUE THREAD

**Issue by 2217895330** [alibaba-damo-academy/3D-Speaker#14]

**Comment by wanghuii1** [comment]
@2217895330 您好，请确认下是否使用egs/voxceleb/sv-cam++/run.sh脚本中stage4-5进行的测试，以及测试模型使用https://modelscope.cn/models/damo/speech_campplus_sv_en_voxceleb_16k/summary中的模型

**Comment by 2217895330** [comment]
模型没错，只不过我是用speakerlab/bin/infer_sv.py里面加载预训练模型的方法加载的，再结合run.sh中的stage4-5做的测试

**Comment by wanghuii1** [comment]
@2217895330 感谢反馈，经核查发现模型错误，现已上传正确的模型，请再次下载使用。
