### ISSUE TITLE
is speech_campplus_speaker-diarization_common onnx model available?

### ISSUE THREAD

**Issue by lancelee98** [alibaba-damo-academy/3D-Speaker#16]
is speech_campplus_speaker-diarization_common onnx model available?

**Comment by wanghuii1** [comment]
Exporting onnx models is not currently supported

**Comment by lancelee98** [comment]
does speech_campplus_sv_zh-cn_16k-commo or speech_campplus-transformer_scl_zh-cn_16k-common support onnx model?

**Comment by wanghuii1** [comment]
not supported now

**Comment by lancelee98** [comment]
thankyou

**Comment by csukuangfj** [comment]
@lancelee98 
We have supported it in https://github.com/k2-fsa/sherpa-onnx/pull/522

We are adding C++ runtime for it.

**Comment by lancelee98** [comment]
> @lancelee98 We have supported it in [k2-fsa/sherpa-onnx#522](https://github.com/k2-fsa/sherpa-onnx/pull/522)
> 
> We are adding C++ runtime for it.
thank you
