### ISSUE TITLE
请问如果我要用CNceleb数据集训练cam++说话人验证模型，那我应该用哪个脚本

### ISSUE THREAD

**Issue by 2217895330** [alibaba-damo-academy/3D-Speaker#17]

**Comment by yfchenlucky** [comment]
可以参考https://github.com/alibaba-damo-academy/3D-Speaker/blob/main/egs/voxceleb/sv-cam%2B%2B/run.sh
本月会发布基于CN-Celeb数据集的各模型训练+测试脚本，star一下敬请期待～
