### ISSUE TITLE
sv-rdino - RuntimeError

### ISSUE THREAD

**Issue by DrinPeng** [alibaba-damo-academy/3D-Speaker#2]
I’ve been trying to train sv-rdino, my code did report such an error at runtime:

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2048]] is at version 3;

How should we solve this problem？

**Comment by yfchenlucky** [comment]
Currently, rdino exclusively supports multi-GPU training. In terms of training time, I highly recommend utilizing 4 GPUs for optimal performance. The problem will be solved.
