### ISSUE TITLE
麻烦问下，3d speaker 开源数据里的标签代表什么意思？

### ISSUE THREAD

**Issue by juzstu** [alibaba-damo-academy/3D-Speaker#22]
比如3D_SPK_07854_005_Device03_Distance03_Dialect09.wav
Device、Distance、Dialect的数字标签分别代表什么？论文里也没说，所以想咨询下。

**Comment by yfchenlucky** [comment]
数据压缩包里面都有对应内容，请仔细阅读：
ANDROID Device01
IPAD Device02
DIRECTIONAL Device03
RP Device04
ARRAY-CH1 Device05
PC Device06
PHONE Device07
IPHONE Device08
ARRAY Device09
-------------------
3.5 Distance01
0.2 Distance02
0.1 Distance03
1.0 Distance04
1.5 Distance05
3.0 Distance06
2.5 Distance07
0.3 Distance08
0.9 Distance09
0.8 Distance10
1.2 Distance11
4.0 Distance12
2.0 Distance13
--------------------
Standard Mandarin Dialect00
Xiang dialect Dialect01
Wu dialect Dialect02
Southwestern Mandarin Dialect03
JiangHuai Mandarin Dialect04
Hakka dialect Dialect05
Central Plains Mandarin Dialect06
Yue dialect Dialect07
Gan dialect Dialect08
Jin dialect Dialect09
Min dialect Dialect10
LiaoJiao Mandarin Dialect11
JiLu Mandarin Dialect12
Northern Mandarin Dialect13

**Comment by yfchenlucky** [comment]
数据压缩包里面都有对应内容，可以仔细阅读：

Standard Mandarin Dialect00
Xiang dialect Dialect01
Wu dialect Dialect02
Southwestern Mandarin Dialect03
JiangHuai Mandarin Dialect04
Hakka dialect Dialect05
Central Plains Mandarin Dialect06
Yue dialect Dialect07
Gan dialect Dialect08
Jin dialect Dialect09
Min dialect Dialect10
LiaoJiao Mandarin Dialect11
JiLu Mandarin Dialect12
Northern Mandarin Dialect13
-------------------
ANDROID Device01
IPAD Device02
DIRECTIONAL Device03
RP Device04
ARRAY-CH1 Device05
PC Device06
PHONE Device07
IPHONE Device08
ARRAY Device09
-------------------
3.5 Distance01
0.2 Distance02
0.1 Distance03
1.0 Distance04
1.5 Distance05
3.0 Distance06
2.5 Distance07
0.3 Distance08
0.9 Distance09
0.8 Distance10
1.2 Distance11
4.0 Distance12
2.0 Distance13

**Comment by juzstu** [comment]
好的，谢谢



---- 回复的原邮件 ----
| 发件人 | Chen ***@***.***> |
| 日期 | 2023年09月04日 11:05 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [alibaba-damo-academy/3D-Speaker] 麻烦问下，3d speaker 开源数据里的标签代表什么意思？ (Issue #22) |

数据压缩包里面都有对应内容，请仔细阅读：
ANDROID Device01
IPAD Device02
DIRECTIONAL Device03
RP Device04
ARRAY-CH1 Device05
PC Device06
PHONE Device07
IPHONE Device08
ARRAY Device09
3.5 Distance01
0.2 Distance02
0.1 Distance03
1.0 Distance04
1.5 Distance05
3.0 Distance06
2.5 Distance07
0.3 Distance08
0.9 Distance09
0.8 Distance10
1.2 Distance11
4.0 Distance12
2.0 Distance13

Standard Mandarin Dialect00
Xiang dialect Dialect01
Wu dialect Dialect02
Southwestern Mandarin Dialect03
JiangHuai Mandarin Dialect04
Hakka dialect Dialect05
Central Plains Mandarin Dialect06
Yue dialect Dialect07
Gan dialect Dialect08
Jin dialect Dialect09
Min dialect Dialect10
LiaoJiao Mandarin Dialect11
JiLu Mandarin Dialect12
Northern Mandarin Dialect13
