### ISSUE TITLE
关于voxceleb dino

### ISSUE THREAD

**Issue by JINzezhong7** [alibaba-damo-academy/3D-Speaker#23]
我最近在复习您的项目，我用voxceleb2 训练dino，但是eer刚开始几轮只有14%。我不确定这是不是正常的，您可以给我一份您的训练日志吗。非常感谢

**Comment by JINzezhong7** [comment]
但是我第一轮是19%，然后到第9轮还有14%。这个正常吗
<img width="1242" alt="image" src="https://github.com/alibaba-damo-academy/3D-Speaker/assets/131787594/69111028-8404-4012-aa19-f8ae50afac04">

**Comment by JINzezhong7** [comment]
我用的是dino，没有用rdino

**Comment by yfchenlucky** [comment]
看趋势是正常范围，可以继续训练，一般25epochs之后，EER会降低到5%以下。

**Comment by JINzezhong7** [comment]
感谢您的回答。我还有两个问题，在mlp那里三层的fc每一层后面都加了bn，这个我没有加影响大吗。还有
<img width="613" alt="image" src="https://github.com/alibaba-damo-academy/3D-Speaker/assets/131787594/109c3dfe-0546-404b-9076-f75ce8bae1c4">
这里我也没有加，请问这里是在做什么。

**Comment by yfchenlucky** [comment]
1. 前两个fc后最好加入bn，没有严格对比过缺失对训练影响。
2. 图中支持多卡batchnorm。

**Comment by JINzezhong7** [comment]
好的谢谢，我发现经过mlp之后得到的是65536dim的向量，然后放入softmax里算分布。为什么最后要选择这么大的一个向量，这是有什么实验证明吗

**Comment by yfchenlucky** [comment]
参照DINO原文中实验配置，我们实验发现如果大幅缩小dim维度，性能会大幅减低。

**Comment by JINzezhong7** [comment]
非常感谢您的回答

**Comment by yfchenlucky** [comment]
不客气，期待您进一步的研究。

**Comment by JINzezhong7** [comment]
<img width="1002" alt="image" src="https://github.com/alibaba-damo-academy/3D-Speaker/assets/131787594/2dcdf43d-b438-4716-a1d8-95feef47f833">
您好，我目前训到19轮 趋势EER 是在降低，但是很慢，并且我发现loss从14 epoch开始升高，这是因为没有加batchnorm吗在head层

**Comment by yfchenlucky** [comment]
是存在可能的，或者是因为你修改代码失误，建议可以先跑完整的源码。

**Comment by JINzezhong7** [comment]
我刚刚踏入这个领域，还想问一个简单的问题，dino在保存模型的时候是保存student model还是teacher model。最后在测试的时候是用teacher model还是student model进行测试呢

**Comment by yfchenlucky** [comment]
都保存，测试使用teacher model，详情见代码哈～
