### ISSUE TITLE
关于learning rate

### ISSUE THREAD

**Issue by JINzezhong7** [alibaba-damo-academy/3D-Speaker#26]
我用了你的cosine schedule之后，我发现我的learning rate 每轮都在增加。但是不应该是从0.2cosine schedule减小到0.00005吗
<img width="169" alt="image" src="https://github.com/alibaba-damo-academy/3D-Speaker/assets/131787594/5e648f75-1910-45ab-9422-f6571f56bc7c">
这个是我的learning rate变化到结果

**Comment by JINzezhong7** [comment]
<img width="646" alt="image" src="https://github.com/alibaba-damo-academy/3D-Speaker/assets/131787594/1554e84d-8ccc-4f07-8a86-37c99035ce91">
<img width="775" alt="image" src="https://github.com/alibaba-damo-academy/3D-Speaker/assets/131787594/8f605deb-5da2-40a8-8e45-0cb213441e6d">
这个是我有关learning rate的代码设置

**Comment by yfchenlucky** [comment]
sv-rdino/speakerlab/utils/utils_rdino.py中函数cosine_scheduler使得learning rate先增后降。
可以仔细阅读代码再提问哈
