### ISSUE TITLE
about the result

### ISSUE THREAD

**Issue by JINzezhong7** [alibaba-damo-academy/3D-Speaker#28]
我复现了一遍代码，我用dino框架，然后mutil crop ：local 2条 （2s) global 1条（3s) ecapa(512). 没有用rdino。 最终的结果是5.0 请问算是一个正常的结果吗

**Comment by yfchenlucky** [comment]
没有跑过上述配置的dino框架，性能属于正常范围。可以尝试：mutil crop ：local 4条 （2s) global 2条（4s) ecapa(512 or 1024).

**Comment by JINzezhong7** [comment]
好的谢谢

**Comment by JINzezhong7** [comment]
batch对结果的影响应该不大吧，我是用一张卡训练的，我按照你的batch =52进行训练的

**Comment by yfchenlucky** [comment]
适当增大batch size会提升性能，但是由于我的显存限制，我是使用52进行训练，如果有条件可以尝试更大显存，可能获得更优结果。

**Comment by JINzezhong7** [comment]
好的谢谢

**Comment by JINzezhong7** [comment]
您好，我发现在测试的时候，代码中显示用到的60轮的模型，请问是因为60轮效果最好吗

**Comment by yfchenlucky** [comment]
是的，你也可以测试一下70epochs，性能差异不大。
