### ISSUE TITLE
Can you consider release the ERes2Net-Base-200k-Spkrs model?

### ISSUE THREAD

**Issue by duj12** [alibaba-damo-academy/3D-Speaker#39]
I noticed that you have released the [ERes2Net-Large-200k-Spkrs model](https://www.modelscope.cn/models/damo/speech_eres2net_sv_zh-cn_16k-common/summary) on modelscope, can you also release the base model of ERes2Net(trained with 200k speakers)?

**Comment by yfchenlucky** [comment]
The ERes2Net-base model is being trained and is expected to be put into modelscope at the end of the month or early next month. If you find this repository useful, please consider giving a star. Thank you for your attention.
