### ISSUE TITLE
[BUG] 提fbank的频率和重采样之后的频率不一致

### ISSUE THREAD

**Issue by cdliang11** [alibaba-damo-academy/3D-Speaker#40]
https://github.com/alibaba-damo-academy/3D-Speaker/blob/b537e3734bc502529bbdb921dca784cb9f67b1b5/speakerlab/bin/infer_sv.py#L165-L176

提fbank的频率始终为16kHz，应该等于重采样之后的频率

**Comment by yfchenlucky** [comment]
为什么会不一致？代码中没有重采样，只是选择单通道wav。可以再具体描述一下您遇到的问题吗？

**Comment by cdliang11** [comment]
> 为什么会不一致？代码中没有重采样，只是选择单通道wav。可以再具体描述一下您遇到的问题吗？

嗷嗷，是我看错，是固定16k采样
