### ISSUE TITLE
如何用这些个模型跑自己的数据集？

### ISSUE THREAD

**Issue by von-321** [alibaba-damo-academy/3D-Speaker#41]
你好，现有自己的数据集，如何用这些个模型跑自己的数据集？3dspeaker 数据集优的文件自己的数据集并没有，例如trials文件等，求教求教！

**Comment by yfchenlucky** [comment]
可以参考3d-speaker准备数据代码：https://github.com/alibaba-damo-academy/3D-Speaker/blob/main/egs/3dspeaker/sv-eres2net/local/prepare_data.sh。trials可以自行生成，如果你有注册集和测试集，可以进行随机搭配组成测试样本对。
