### ISSUE TITLE
关于ERes2Net的250k新模型

### ISSUE THREAD

**Issue by axuan731** [alibaba-damo-academy/3D-Speaker#44]
您好：
首先特别感谢您在modelscope中贡献的模型及代码。
我看到modelscope最近更新了ERes2Net的250k模型：“speech_eres2net_base_250k_sv_zh-cn_16k-common”
下面是使用该模型在本地推理的代码：
```
model_id=damo/speech_eres2net_base_250k_sv_zh-cn_16k-common
python speakerlab/bin/infer_sv.py --model_id $model_id --wavs $wav_path
```
但是我发现这个模型缺少了一些必要命令，如：
```
ERes2Net_Large_3D_Speaker = {
    'obj': 'speakerlab.models.eres2net.ResNet.ERes2Net',
    'args': {
        'feat_dim': 80,
        'embedding_size': 512,
        'm_channels': 64,
    }
```
和
`supports = {...}`
希望得到您的帮助，非常感谢~

**Comment by yfchenlucky** [comment]
speech_eres2net_base_250k_sv_zh-cn_16k-common 该模型未更新至最新状态，请稍候几天，下周可以提供正常使用，感谢您的关注。
