### ISSUE TITLE
damo/speech_eres2net_sv_zh-cn_16k-common 模型不支持输入numpy数组

### ISSUE THREAD

**Issue by kwaihua** [alibaba-damo-academy/3D-Speaker#46]
隔壁cam++推理时，可以直接输入提取好的音频numpy数组进行推理。
希望eres2net也可以统一加上，谢谢

**Comment by yfchenlucky** [comment]
您好，我check了modelscope上damo/speech_eres2net_sv_zh-cn_16k-common模型推理代码，是支持numpy数组输入的，所以不知道具体问题出现在哪里？
