### ISSUE TITLE
DDP WARNING

### ISSUE THREAD

**Issue by JINzezhong7** [alibaba-damo-academy/3D-Speaker#47]
您好，非常感谢您补充了ecapatdnn，我在训练egs中voxceleb ecapatdnn中遇到了这个warning，我不知道是因为什么
<img width="1435" alt="image" src="https://github.com/alibaba-damo-academy/3D-Speaker/assets/131787594/f543c457-5183-4949-b99c-bc081ebc4ba1">

**Comment by yfchenlucky** [comment]
这个warning对训练没有影响，您可以训练完测试模型性能。如果觉得该项目对您有帮助，记得star关注一下喔！

**Comment by JINzezhong7** [comment]
非常感谢您对回复，我训练ecapa(1024) 在vox1+vox2数据集上 在ffsvc2022 dev上测试效果很差。您有在这个数据集上面测试过吗

**Comment by yfchenlucky** [comment]
没有在ffsvc2022 dev测试过，可能是数据不同源导致，如果ffsvc2022有训练集，可以加入模型训练，如果没有的话建议采用我们在modelscope上发布的预训练模型进行测试：https://modelscope.cn/models/damo/speech_eres2net_sv_zh-cn_16k-common/summary。
