### ISSUE TITLE
请问可以分离出指定人的语音吗

### ISSUE THREAD

**Issue by cx-cs** [alibaba-damo-academy/3D-Speaker#48]
在多人说话重叠的场景是否可以分离出指定说话人的声音？

**Comment by yfchenlucky** [comment]
通过 https://github.com/alibaba-damo-academy/3D-Speaker/tree/main/egs/3dspeaker/speaker-diarization 代码可以将一段话中的各说话人语音分离，如果你想分离出置顶说话人声音，可以通过提取指定说话人的speaker embedding和各聚类中心比较，选择最近的类，再获取其相应语音片段。
