### ISSUE TITLE
Exmaple can not run

### ISSUE THREAD

**Issue by luohao123** [alibaba-damo-academy/3D-Speaker#53]
Stage5: Get the final metrics...
Refrttm.list is not detected. Can't calculate the result

**Comment by yfchenlucky** [comment]
Have you followed these commands in the Readme?

mkdir examples
wget "https://modelscope.cn/api/v1/models/damo/speech_eres2net-large_speaker-diarization_common/repo?Revision=master&FilePath=examples/example.wav" -O examples/example.wav
wget "https://modelscope.cn/api/v1/models/damo/speech_eres2net-large_speaker-diarization_common/repo?Revision=master&FilePath=examples/example.rttm" -O examples/example.rttm
find examples -name "*.wav" > examples/wav.list
find examples -name "*.rttm" > examples/refrttm.list

**Comment by luohao123** [comment]
I think it's tooooo messy for runing a wav to diarization,. better learn something from FunASR? it's same company but the opensource project got so much various quality.
