### ISSUE TITLE
fine-tune

### ISSUE THREAD

**Issue by JINzezhong7** [alibaba-damo-academy/3D-Speaker#65]
您好，我再训练完dino之后想用label数据fine-tune，如何加载之前的模型.pth

**Comment by yfchenlucky** [comment]
可以参考https://github.com/alibaba-damo-academy/3D-Speaker/blob/main/speakerlab/bin/train_rdino.py 第115行restart_from_checkpoint函数。

**Comment by JINzezhong7** [comment]
我可以参考extract_rdino.py 中的加载模型的代码吗，因为fine-tune需要加classifier，不需要dino head

**Comment by yfchenlucky** [comment]
都是可以的，哪个更适合你就选择哪个，have a try~
