### ISSUE TITLE
how to extract embeddings by ecapa or resnet

### ISSUE THREAD

**Issue by JuneAndJuly** [alibaba-damo-academy/3D-Speaker#66]
The old model extracting speaker features is no longer supported

**Comment by yfchenlucky** [comment]
Could you please provide a detailed description of your issue? Is it an error with the code or with the model?

**Comment by JuneAndJuly** [comment]
> Could you please provide a detailed description of your issue? Is it an error with the code or with the model?

![image](https://github.com/alibaba-damo-academy/3D-Speaker/assets/33370520/59eab37c-93a1-4b3f-9259-63e30636af42)
![image](https://github.com/alibaba-damo-academy/3D-Speaker/assets/33370520/603cb16f-110c-4055-a043-a978fcb5f08c)
I extracted the speaker vector based on this, but ecapa is not in supports

**Comment by yfchenlucky** [comment]
We update the infer_sv.py and you can try again for ecapa-tdnn model. ResNet and Res2net will release next month.

**Comment by uuuzk** [comment]
> We update the infer_sv.py and you can try again for ecapa-tdnn model. ResNet and Res2net will release next month.

请问ResNet和Res2net模型权重公布了吗？我目前还是没找到相应权重代码，或者有计划公布吗？
