### ISSUE TITLE
准备cnceleb wav

### ISSUE THREAD

**Issue by JINzezhong7** [alibaba-damo-academy/3D-Speaker#68]
我发现在准备cnceleb的时候，flac2wav 那一步，在local下没有flac2wav.py 文件，我使用sv-ecapa下的文件的时候发现有部分flac无法转换成wav文件

**Comment by yfchenlucky** [comment]
感谢您的提醒，已经将flac2wav.py文件上传。flac无法转wav文件具体报错是什么呢？您可以检查到具体wav文件，判断是否是因为wav文件下载出错而引发的错误，期待进一步的交流。

**Comment by JINzezhong7** [comment]
感谢您的及时回复，我发现在flac转wav结束之后，有一些wav文件 是empty
<img width="914" alt="image" src="https://github.com/alibaba-damo-academy/3D-Speaker/assets/131787594/02bd06d2-b793-4546-985d-e1953f8cbbe7"> 但我测试flac相同的文件 是正常的

**Comment by yfchenlucky** [comment]
你可以cd CN-Celeb2_flac/data/id11978 查看flac文件是否正常：ls -al entertainment-02-002.flac 32298 Sep 19 15:17 entertainment-02-002.flac。可能是下载的flac文件异常导致wav异常，数据下载和转换代码应该没有问题，期待你的回复。
