### ISSUE TITLE
information about room acoustics in the dataset

### ISSUE THREAD

**Issue by sivannavis** [alibaba-damo-academy/3D-Speaker#78]
Hi, thanks for the repo! Is the whole dataset recorded in the same room or different room? Could you also tell me if the room is anechoic and what type of room it is? Thank you!

**Comment by GeekOrangeLuYao** [comment]
Thank you for your interest in the 3D-Speaker. Our data was recorded in various rooms and the recording process included multiple batches. For some of these batches, we did not maintain explicit and detailed records of the acoustic environment in which the recordings were made, so we are currently unable to answer your second question. If in the future we decide to organize and release additional room acoustic information for some of the audio, we will announce it on our [website](https://3dspeaker.github.io/).
