### ISSUE TITLE
sv-rdino trainning data.

### ISSUE THREAD

**Issue by hcfeng201** [alibaba-damo-academy/3D-Speaker#80]
Regarding sv-rdino, how many data(persons and utts) are needed to achieve an EER below 10%? Have you conducted any experiments on this?

**Comment by yfchenlucky** [comment]
According to VoxCeleb, the Equal Error Rate (EER) typically falls below the 10% threshold after approximately 10 training epochs. For other datasets, no relevant conclusions can be drawn regarding this trend.
