### ISSUE TITLE
eres2net模型是否支持mp3

### ISSUE THREAD

**Issue by xztzmr** [alibaba-damo-academy/3D-Speaker#82]
from modelscope.pipelines import pipeline
sv_pipline = pipeline(
    task='speaker-verification',
    model='damo/speech_eres2net_large_sv_zh-cn_3dspeaker_16k',
    #model_revision='v1.0.5'
)
result = sv_pipline(['/mnt/workspace/a.mp3', '/mnt/workspace/b.mp3'])
执行这个命令16G显存满了

**Comment by yfchenlucky** [comment]
支持mp3格式输入，可能是因为你音频太长导致显存out of memory. 可以考虑缩减音频长度，因speech_eres2net_large_sv_zh-cn_3dspeaker_16k参数量较大，后续会上线其剪枝模型，敬请期待。

**Comment by xztzmr** [comment]
好的多谢
