### ISSUE TITLE
sv-eres2net训练异常

### ISSUE THREAD

**Issue by canglangzhishuiz** [alibaba-damo-academy/3D-Speaker#85]
**数据集**：voxceleb
**训练脚本**: [sv-eres2net](https://github.com/alibaba-damo-academy/3D-Speaker/tree/main/egs/voxceleb/sv-eres2net)
运行bash run.sh后，控制台输出如下，一直没有更新：
<img width="837" alt="截屏2024-03-26 15 57 18" src="https://github.com/alibaba-damo-academy/3D-Speaker/assets/64078820/d76f3cb8-796b-4f85-b659-eec1ab10302e">
nvitop显示如下，也一直没有更新:
<img width="1035" alt="截屏2024-03-26 16 00 43" src="https://github.com/alibaba-damo-academy/3D-Speaker/assets/64078820/1ef1373a-14ca-4745-b76a-c75a0f67329f">
请问这种情况正常吗？

**Comment by canglangzhishuiz** [comment]
我的GPU上无其它进程，是不是和显卡有关系，我的训练设备为h800

**Comment by yfchenlucky** [comment]
H800也可以正常运行吧，你重新启动程序试试呢？你的GPU利用率是100%，还有其他程序在运行？你可以好好检查有无输出日志：3D-Speaker/egs/voxceleb/sv-eres2net/exp/eres2net/train.log。

**Comment by canglangzhishuiz** [comment]
cat exp/eres2net/train.log 
<img width="419" alt="截屏2024-03-26 17 06 48" src="https://github.com/alibaba-damo-academy/3D-Speaker/assets/64078820/ae88ee9c-eaf0-43ae-8562-23d5adbbbf84">
镜像和程序都尝试重启过，输出都一样。

**Comment by yfchenlucky** [comment]
可以参考：https://github.com/Lightning-AI/pytorch-lightning/discussions/11865

**Comment by canglangzhishuiz** [comment]
好的，非常感谢🙏🙏🙏
