### ISSUE TITLE
modelscope如何调用自己训练的模型

### ISSUE THREAD

**Issue by canglangzhishuiz** [alibaba-damo-academy/3D-Speaker#86]
```python
from modelscope import pipeline

predictor = pipeline(task='speaker-verification', model="egs/voxceleb/sv-eres2net/exp/eres2net/models/CKPT-EPOCH-70-00")

TypeError: type must be a str or valid type, but got <class 'NoneType'>
```
ls egs/voxceleb/sv-eres2net/exp/eres2net/models/CKPT-EPOCH-70-00
```text
CKPT.yaml
classifier.ckpt
embedding_model.ckpt
epoch_counter.ckpt
```
需要转换格式吗？还是只能像infer_sv.py那样，torch.load一步一步加载

**Comment by yfchenlucky** [comment]
modelscope调用model得在modelscope平台建立model card，然后按照流程做完之后才可以调用，不是简单替换哈。

**Comment by canglangzhishuiz** [comment]
好的，我的一个eres2net模型权重，为何只有几十MB，而modelscope上[speech_eres2net_sv_zh-cn_16k-common](https://www.modelscope.cn/models/iic/speech_eres2net_sv_zh-cn_16k-common/files)这个模型权重200多MB，模型不是都一样吗，为何差别这么大

**Comment by yfchenlucky** [comment]
ModelScope中eres2net-200k-common模型是基于ERes2Net-base的扩展模型，所以参数量和计算量较大，https://www.modelscope.cn/models/iic/speech_eres2net_base_200k_sv_zh-cn_16k-common/summary
是ERes2Net-base模型。后续我们会开源ERes2NetV2，可以持续关注，点点star。
