### ISSUE TITLE
关于exp decrease learning schedule

### ISSUE THREAD

**Issue by JINzezhong7** [alibaba-damo-academy/3D-Speaker#89]
您好，最近在研究您的代码，我发现learning rate scheduler只有warmup cosine。 请问可以提供一下其他的吗 比如exp decrease。

**Comment by yfchenlucky** [comment]
暂无其他模式，您可以在此基础上自行修改。

**Comment by yfchenlucky** [comment]
> 您好，最近在研究您的代码，我发现learning rate scheduler只有warmup cosine。 请问可以提供一下其他的吗 比如exp decrease。

https://github.com/alibaba-damo-academy/3D-Speaker/blob/main/speakerlab/process/scheduler.py#L49-L51
