### ISSUE TITLE
关于人脸相关模型输入通道的问题。

### ISSUE THREAD

**Issue by hao-qiang** [alibaba-damo-academy/3D-Speaker#95]
https://github.com/alibaba-damo-academy/3D-Speaker/blob/4590d1cbb89fd9176a9d57573969b1b8790bf68d/egs/3dspeaker/speaker-diarization/local/vision_tools/face_quality_assessment.py#L18-L20

在人脸质量评估和人脸特征提取模型的输入数据处理的地方，通道被转换了两次，相当于没有变，请问这两个模型的输入通道是RGB还是BGR。

**Comment by wanghuii1** [comment]
感谢指正。此处应该是一个错误，对比模型源码，网络输入应是RGB。不过经过对比，这个错误产生的误差非常小。目前代码已经更正，并对输入格式进行了注释。
